### ISSUE TITLE
본문의 넓이 비율 변경

### ISSUE THREAD

**Issue by HEROHJK** [FSFMS/readme-contents#8]
본문이 조금 더 Wide 했으면 좋겠습니다.

<img width="977" alt="스크린샷 2022-06-05 오후 5 07 25" src="https://user-images.githubusercontent.com/14340282/172041622-7fd37361-3d49-405c-854b-9cd133661979.png">

위 화면에서 빨간영역을 위젯,
파란 영역을 본문이라고 정의 했을 때..

2:8 정도의 비율이면 좋겠습니다.

**Comment by nomore12** [comment]
@HEROHJK 비율 변경 완료. 이슈 체크 바랍니다.
